import os
import sys
import platform

OS_NAME = platform.system();
env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

SOURCES= Glob("audio_decoders/*.c") + \
  Glob("audio_device/*.c") + \
  Glob("audio_encoders/*.c") + \
  Glob("audio_player/*.c") + \
  Glob("audio_recorder/*.c") + \
  Glob("base/*.c") + \
  Glob("lrc/*.c") + \
  Glob("widgets/*.c") + \
  Glob('*.c')

if os.environ['WITH_FFMPEG'] == 'true':
  SOURCES+=Glob("ffmpeg/*.c") 

EXPORT_DEF=''
if OS_NAME == 'Windows':
  EXPORT_DEF = ' /DEF:"src/media_player.def" '

LINKFLAGS=env['LINKFLAGS'] + EXPORT_DEF 
env.SharedLibrary(os.path.join(BIN_DIR, 'media_player'), SOURCES, LINKFLAGS=LINKFLAGS)

