import os   
import platform
sources=[]
OS_NAME=platform.system()
env=DefaultEnvironment().Clone()

LIB_DIR=os.environ['LIB_DIR'];
sources=Glob("src/*.c")+\
Glob('src/atomic/*.c')+\
Glob('src/audio/*.c')+\
Glob('src/cpuinfo/*.c')+\
Glob('src/events/*.c')+\
Glob('src/file/*.c')+\
Glob('src/libm/*.c')+\
Glob('src/power/*.c')+\
Glob('src/render/*.c')+\
Glob('src/render/software/*.c')+\
Glob('src/stdlib/*.c')+\
Glob('src/thread/*.c')+\
Glob('src/timer/SDL_timer.c')+\
Glob('src/video/yuv2rgb/*.c')+\
Glob('src/video/*.c')+\
Glob('src/loadso/dlopen//*.c')+\
Glob('src/audio/dummy/*.c')+\
Glob('src/video/dummy/*.c')+\
Glob('src/core/linux/*.c')+\
Glob('src/thread/pthread/*.c')+\
Glob('src/power/linux/*.c')+\
Glob('src/filesystem/unix/*.c')+\
Glob('src/timer/unix/*.c')+\
Glob('src/core/unix/*.c')+\
Glob('src/audio/alsa/*.c')+\
Glob('src/main/dummy/*.c')

env.Library(os.path.join(LIB_DIR, 'SDL2'), sources)

