import os
import sys
import platform

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env['LIBS'] = ['media_player'] + env['LIBS']
if os.environ['WITH_FFMPEG'] == 'true':
  env.Program(os.path.join(BIN_DIR, 'demo_media_player'), ['demo_media_player.c'])

env.Program(os.path.join(BIN_DIR, 'demo_audio_player'), ['demo_audio_player.c'])
env.Program(os.path.join(BIN_DIR, 'demo_audio_recorder'), ['demo_audio_recorder.c'])


