import os
import sys
import platform

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

if os.environ['WITH_FFMPEG'] == 'true':
  env.Program(os.path.join(BIN_DIR, 'demo_media_player'), ['demo_media_player.c'])

env.Program(os.path.join(BIN_DIR, 'demo_audio_player'), ['demo_audio_player.c'])


